Add/competition nbs
radiantearth/mlhub-tutorials pull request #84
Opened 2023-02-16 17:53 UTC by DanielNwaeze

updated nasa harvest notebook with helpful markdowns

2023-02-17 00:38 UTC, PowerChell commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<ul><li>Change to "Sentintel-2 time series" </li><li>hyperlink to competition dataset here at the end</li></ul>
<br/>

 _Reply via <a href='https://app.reviewnb.com/radiantearth/mlhub-tutorials/pull/84/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2023-02-17 00:38 UTC, PowerChell commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<p>Remove this cell. We have this information in the general readme for the tutorial notebooks.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/radiantearth/mlhub-tutorials/pull/84/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2023-02-17 00:38 UTC, PowerChell commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<p>For the Authentication deciton, copy and paste the cell titled "Authentication" from the <a href="https://github.com/radiantearth/mlhub-tutorials/blob/main/tutorials/Guide%20to%20Building%20a%20Basic%20Machine%20Learning%20Model/radiant-mlhub-basic-model-training.ipynb" target="_blank">other ML nb</a> and also how the API key is entered (copy and paste that cell from the other notebook and remove that line here). We want all the notebooks to have a similar flow between them.</p><p> </p><p>Then, have a separate cell with the dataset_id and dataset fetch. The comment in this section should be "# Define the dataset id and fetch the dataset". </p><p> </p><p>Before this cell, add the following markdown section:</p><p> </p><h2>Data Download</h2><p>Now that your API credentials have been specified, we will download the data from the&nbsp;<a href="https://mlhub.earth/" target="_blank">Radiant-MLHub</a>&nbsp;API through Python.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/radiantearth/mlhub-tutorials/pull/84/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='5'/>

2023-02-17 00:38 UTC, PowerChell commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<p>Change comment to "# Define the image snapshot dimensions and the RBGA Bands"</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/radiantearth/mlhub-tutorials/pull/84/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='7'/>

2023-02-17 00:38 UTC, PowerChell commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<p>Find my suggested rewording for this cell below. Please read through and make any changes for sections that perhaps changed the meaning of the explanation. I changed it to flow better, but I want to make sure we are not losing any important information!</p><p> </p><p>I still do not understand the last section of this cell. Please try rewording it. I am happy to jump on a call to talk it out too to see if we can come up with a better explanation together :) </p><p> </p><p> </p><h2>The Training Data</h2><p> </p><p>We have two sets of data: the <code>train</code> and <code>test</code> datasets.&nbsp;&nbsp;</p><p> </p><p>For model development purposes, we will use the training source imagery and label set (<code>source_train</code> and <code>labels_train</code>) for the model development and use the test set (<code>source_teset</code>) for model prediction/evaluation.</p><p> </p><p>(This section below is the one I am still confused on)</p><p> </p><p><em>This method is preferred since it saves memory by not training additional imagery and it also prevents the model from overfitting. Having a separate test dataset which the model hasn't previously seen for prediction also helps give a fair assessment of the performance of the model.</em></p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/radiantearth/mlhub-tutorials/pull/84/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='8'/>

2023-02-17 00:38 UTC, PowerChell commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<p>Add title to this cell: ### Create List of Unique Training IDs</p><p> </p><p>I am still a bit confused on the unique IDs. Do the unique IDs contain the YYYY_MM or not? let me know and then I may have some comments</p><p> </p><p>Rewording for middle section:</p><p> </p><p>"The corresponding training label files do not inclue any date in the name of the file. Therefore, the training label files follow the convention <code>nasa_rwanda_field_boundary_competition_label_train_ID</code>. By striping the <code>YYYY_MM</code> component from out from our unique ID (going from <code>ID_YYYY_MM</code> to simply <code>ID</code>), we can use the unique ID&nbsp;to obtain the corresponding label file for the source imagery.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/radiantearth/mlhub-tutorials/pull/84/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='10'/>

2023-02-17 00:38 UTC, PowerChell commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<p>Suggested rewording:</p><p> </p><p>### Normalize the Source Imagery</p><p> </p><p>We will need to normalize our source imagery to remove any pixel values that are greater than 255. We apply the min-max normalisation calculation for each image:&nbsp;&nbsp;</p><p> </p><p>$${\text{all pixel values - minimum pixel value} \over \text{maximum pixel value - minimum pixel value}}$$&nbsp;&nbsp;</p><p> </p><p>This normalization ensures that our image is uniformly distributed and displays the "normal" image. If we do not normalize the image, we will be working with distorted images that would add no value to the model during model training.&nbsp;&nbsp;</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/radiantearth/mlhub-tutorials/pull/84/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='14'/>

2023-02-17 00:38 UTC, PowerChell commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<p>Add header ### Augmentation Techniques</p><p> </p><p>What is "this" in the second sentence. Reword this first section. We can chat it out together if you'd like!</p><p> </p><p><strong>Suggested rewording for the rest of the section :</strong></p><p> </p><p>In this notebook, we will perform data augmentation on our normalized images. This will be used to populate the model with data for training to obtain even more accurate results.</p><p> </p><p>We will employ the following data augmentation techniques on the dataset:</p><p>- Rotation</p><p>- Flipping</p><p>- Blurring</p><p> </p><p>These techniques were developed by thanks to the [radix-ai](https://github.com/radix-ai/agoro-field-boundary-detector).</p><p> </p><p>We will input the post-normalization 4-band stack of each image. The 4 bands in this stack will include:</p><p>- B01 (Ultra Blue (Coastal and Aerosol))</p><p>- B02 (Blue)</p><p>- B03 (Green) and</p><p>- B04 (Red)</p><p> </p><p>The results of a random source image and its associated label below.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/radiantearth/mlhub-tutorials/pull/84/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='16'/>

2023-02-17 00:38 UTC, PowerChell commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<p>Remove the comments in this cell</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/radiantearth/mlhub-tutorials/pull/84/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='17'/>

2023-02-17 00:38 UTC, PowerChell commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<p>Add a space after each dash to transform into bullet points in markdown</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/radiantearth/mlhub-tutorials/pull/84/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='18'/>

2023-02-17 00:38 UTC, PowerChell commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<p>Instead of having this link as a comment in the cell, either delete it or make a Markdown cell above explaining it and linking there.</p><p> </p><p>Remove or move the inline comments in this cell. Avoid inline comments as much as possible in Python (see PEP8 style guide).</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/radiantearth/mlhub-tutorials/pull/84/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='19'/>

2023-02-17 00:38 UTC, PowerChell commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<p>Remove the comment here and turn into a Markdown cell above. </p><p> </p><p>Suggested wording:</p><p> </p><p>The function <code>show_image</code> below allows us to display an RGB image. Below, the <code>add_subplot</code> attributes define the left and the right side of the image.&nbsp;</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/radiantearth/mlhub-tutorials/pull/84/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='20'/>

2023-02-17 00:38 UTC, PowerChell commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<p>Move inline comments and change formatting of comments to be PEP8 compliant (<code># + space + capital letter</code> in a sentence like format) </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/radiantearth/mlhub-tutorials/pull/84/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='30'/>

2023-02-17 00:38 UTC, PowerChell commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<p>same comment as above</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/radiantearth/mlhub-tutorials/pull/84/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='31'/>

2023-02-17 00:38 UTC, PowerChell commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<ul><li>First sentence reword: "The U-Net model has been selected in this training for its impressive results over multiple domains in image segmentation."</li><li>In the third sentence: "This ___ uses". This what? Always use a noun after the word "this". Same issue a few lines down as well.</li><li>Is there a better word instead of "channels"? I am a bit confused on that one</li><li>I wonder if this last sentence would be better placed up near the top of the notebook where you discuss the need for normalization of the data! I find that section a bit confusing, yet this line would clarify some</li></ul>
<br/>

 _Reply via <a href='https://app.reviewnb.com/radiantearth/mlhub-tutorials/pull/84/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='33'/>

2023-02-17 00:38 UTC, PowerChell commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #1.    #https://github.com/sustainlab-group/ParcelDelineation/blob/master/models/unet.py
</pre><p> </p><p>Move this link to a markdown cell above and explain why its included.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/radiantearth/mlhub-tutorials/pull/84/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='37'/>

2023-02-17 00:38 UTC, PowerChell commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<ul><li>Add sub-header to this section</li><li>"which were labelled were actually predicted as well" do you mean to say "which were labelled were actually predicted correctly"?</li><li>remove "ie"s </li><li>keep capitalization on F1 consistent </li></ul>
<br/>

 _Reply via <a href='https://app.reviewnb.com/radiantearth/mlhub-tutorials/pull/84/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='40'/>

2023-02-17 00:38 UTC, PowerChell commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #1.    #https://datascience.stackexchange.com/questions/45165/how-to-get-accuracy-f1-precision-and-recall-for-a-keras-model
</pre><p>same comment as earlier. make into markdown cell and explain link</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/radiantearth/mlhub-tutorials/pull/84/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='41'/>

2023-02-17 00:38 UTC, PowerChell commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<ul><li>Capitalize proper nouns (F1 and U-Net)</li><li>Break up these "we will" sentences to above which cell it is happening so you can remove the "we will" structure </li><li>Last sentence reword: "Not using enough epochs doesn't allow the model to learn enough about the dataset, which will lead to underfitting. On the other hand, too many epochs makes the model understand too much about the data, which will lead to overfitting."</li></ul>
<br/>

 _Reply via <a href='https://app.reviewnb.com/radiantearth/mlhub-tutorials/pull/84/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='42'/>

2023-02-17 00:38 UTC, PowerChell commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #7.    #sm.metrics.FScore(beta=1)
</pre><p>remove this line</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/radiantearth/mlhub-tutorials/pull/84/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='43'/>

2023-02-17 00:38 UTC, PowerChell commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<p>directory we are working in</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/radiantearth/mlhub-tutorials/pull/84/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='48'/>

2023-02-17 00:38 UTC, PowerChell commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<p>final step is to apply the model prediction on the dataset</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/radiantearth/mlhub-tutorials/pull/84/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='52'/>

2023-02-17 02:46 UTC, PowerChell commented
Hey @DanielNwaeze ! I made notes throughout the doc, but here are a few general notes to consider as well: 

- Take a look at [PEP8 style guide](https://peps.python.org/pep-0008/) for general Python styling tips. This document is why I recommend you remove your inline comments and why all the comments I make have a space after the # and the first letter is capitalized.
- Reduce the "we will" style of sentence as much as possible.
- Add subheadings wherever possible to continue to guide the user.

I am available to meet tomorrow or next week to discuss anything that is not clear or you would like help with. :)

2023-02-17 14:20 UTC, DanielNwaeze commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<p>@PowerChell</p><p>I don't think you understand what the last section means because you're not familiar with what overfitting is (this is a machine learning term).</p><p>The following is a better wording:</p><p><em>Having a separate test dataset which the model hasn't previously seen for prediction also helps us observe the model's results and confirm if they are what we expect.</em></p>

2023-02-17 14:23 UTC, DanielNwaeze commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<p>As said earlier, *each field where a unique ID is of the format&nbsp;<code>ID_YYYY_MM</code>*</p>

2023-02-17 14:30 UTC, DanielNwaeze commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<p>Excluding "This normalization ensures that our image is uniformly distributed and displays the "normal" image." as it's redundant</p>

2023-02-17 14:38 UTC, DanielNwaeze commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<p>this == data augmentation from the first sentence. First section is reworded better as:</p><p><em>Here, data augmentation will be used to populate the model with data using our normalised images for training to obtain even more accurate results.</em></p><p> </p><p>Last section is written better as: <em>The results of a random source image and its associated label can be seen below.</em></p>

2023-02-17 14:46 UTC, DanielNwaeze commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<p>link comment deleted as the base repository has been referenced already in the notebook. Also, inline comments moved down</p>

2023-02-17 14:59 UTC, DanielNwaeze commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<p>changing image's unique ID to ID instead as it can generate confusion with the initial definition of unique ID (<code>ID_YYYY_MM</code>)</p>

2023-02-17 15:03 UTC, DanielNwaeze commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<p>Adding your suggestion and fixing minor typos in your suggestion</p>

2023-02-17 15:13 UTC, DanielNwaeze commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<p>Channels is the only technically right word to use in this ML specific context, anything else isn't really correct.</p><p>Batch normalisation is also very different from the image data normalisation we discussed about. It again, is an ML specific term</p>

2023-02-17 15:27 UTC, DanielNwaeze commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<p>done and reworded</p><p> </p><p>"The model's architecture below was tweaked from [sustainlab-group](https://github.com/sustainlab-group/ParcelDelineation/blob/master/models/unet.py) using our number of bands and channels."</p>

2023-02-17 15:36 UTC, DanielNwaeze commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<p>"Model Evaluation Metrics" is the ideal sub-header.</p><p>Also fixed the notebook using the other suggestions</p>

2023-02-17 16:04 UTC, DanielNwaeze commented on tutorials/Guide to Building a Basic Machine Learning Model/NASA-harvest/Nasa_Harvest_Model_MLHub.ipynb
> +{
<p>Including test dataset is important, rewording to "The final step is to apply the model prediction on the test dataset."</p>

2023-02-22 16:22 UTC, PowerChell requested changes
Hi @DanielNwaeze, looking great! Just a few final fixes (see ReviewNB). If the comments arent showing up on the ReviewNB, let me know.

2023-02-22 17:31 UTC, DanielNwaeze commented
Hey Michelle

I can't see the comments on ReviewNB. Checked multiple times

On Wed, Feb 22, 2023 at 5:22 PM Michelle Roby ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @DanielNwaeze <https://github.com/DanielNwaeze>, looking great! Just a
> few final fixes (see ReviewNB). If the comments arent showing up on the
> ReviewNB, let me know.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/radiantearth/mlhub-tutorials/pull/84#pullrequestreview-1309625630>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANW4F53NEBWBDWLTQS6LHWDWYY4LJANCNFSM6AAAAAAU6POI2Y>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-22 19:59 UTC, PowerChell commented
Hey @DanielNwaeze, here are those final comments. Mainly just removing the final inline comments. Also, please remove the last cell that is empty at the end of the notebook. 
![Screen Shot 2023-02-22 at 1 58 04 PM](https://user-images.githubusercontent.com/42818395/220744884-6e1700e2-4d5d-42bc-978c-44db49b779a3.png)
![Screen Shot 2023-02-22 at 1 57 44 PM](https://user-images.githubusercontent.com/42818395/220744894-1c84c344-49dc-448e-861f-4cbca74d2463.png)
![Screen Shot 2023-02-22 at 1 57 30 PM](https://user-images.githubusercontent.com/42818395/220744897-3e788528-f318-4a6f-97ea-4d4a1c384e40.png)
![Screen Shot 2023-02-22 at 1 57 13 PM](https://user-images.githubusercontent.com/42818395/220744899-a7c82b20-d18a-488b-8ba7-e025ad4a8f9f.png)

2023-02-22 21:16 UTC, DanielNwaeze commented
I have made the changes.
Pretty sure I also did some of those changes earlier, no idea why it didn't
reflect (Jupyter fail save maybe).

Also, I'm not sure if ReviewNB has the functionality of modifying
code/markdowns directly from comments but it would be really nice if they
did, similar to Google docs, it would be easier to track suggestions and
modifications as well.

Don't think the notebook has any issues now so I'll continue working on the
AgriFieldNet while keeping in mind your comments on the harvest notebook,
thanks.

On Wed, Feb 22, 2023 at 9:00 PM Michelle Roby ***@***.***>
wrote:

> Hey @DanielNwaeze <https://github.com/DanielNwaeze>, here are those final
> comments. Mainly just removing the final inline comments. Also, please
> remove the last cell that is empty at the end of the notebook.
> [image: Screen Shot 2023-02-22 at 1 58 04 PM]
> <https://user-images.githubusercontent.com/42818395/220744884-6e1700e2-4d5d-42bc-978c-44db49b779a3.png>
> [image: Screen Shot 2023-02-22 at 1 57 44 PM]
> <https://user-images.githubusercontent.com/42818395/220744894-1c84c344-49dc-448e-861f-4cbca74d2463.png>
> [image: Screen Shot 2023-02-22 at 1 57 30 PM]
> <https://user-images.githubusercontent.com/42818395/220744897-3e788528-f318-4a6f-97ea-4d4a1c384e40.png>
> [image: Screen Shot 2023-02-22 at 1 57 13 PM]
> <https://user-images.githubusercontent.com/42818395/220744899-a7c82b20-d18a-488b-8ba7-e025ad4a8f9f.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/radiantearth/mlhub-tutorials/pull/84#issuecomment-1440718534>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANW4F535TQ4JCD7OMYTGDF3WYZV4HANCNFSM6AAAAAAU6POI2Y>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-03-01 16:01 UTC, merged